unsplash:
  api:
    url: https://api.unsplash.com
  url: https://unsplash.com
  token: nBxq3ZTiMC0zoDVmdLF-GC8xS-UBVEmo467ltBX2NRI

spring:
  security:
    oauth2:
      client:
        registration:
          unsplash:
            client-id: JV4_fEdaoOO-r-VBd1yTFxOju8VAEtdCvWwBvrZU1FE
            client-secret: 5KXC66TVZ8BkYK6ISXakRT6q9juPaxDI--oaK3xRIY0
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/unsplash
            scope: public, read_collections
        provider:
          unsplash:
            authorization-uri: https://unsplash.com/oauth/authorize
            token-uri: https://unsplash.com/oauth/token